[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd api && npm install']

[phases.build]
cmds = ['cd api && npm run build']

[start]
cmd = 'cd api && echo "CWD is $(pwd)" && ls -la && echo "Listing dist:" && ls -la dist && npm run start:prod'
