[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"
watchPatterns = ["src/**", "prisma/**", "package.json"]

[deploy]
startCommand = "cd api && npm run start:prod"
healthcheckPath = "/"
restartPolicyType = "on_failure"
