[build]
builder = "nixpacks"
watchPatterns = ["src/**", "prisma/**", "package.json"]

[deploy]
startCommand = "npx prisma migrate deploy && npm run start:prod"
healthcheckPath = "/"
restartPolicyType = "on_failure"
