[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"
watchPatterns = ["src/**", "prisma/**", "package.json"]

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "on_failure"
